import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const sfPRO = localFont({
  src : [
    {
      path : "/fonts/sf-pro-display_thin.woff2",
      weight : "100",
      style : "normal",
    },
    {
      path : "/fonts/sf-pro-display_light.woff2",
      weight : "300",
      style : "normal",
    },
    {
      path : "/fonts/sf-pro-display_regular.woff2",
      weight : "400",
      style : "normal",
    },
    {
      path : "/fonts/sf-pro-display_medium.woff2",
      weight : "500",
      style : "normal",
    },
    {
      path : "/fonts/sf-pro-display_semibold.woff2",
      weight : "600",
      style : "normal",
    },
    {
      path : "/fonts/sf-pro-display_bold.woff2",
      weight : "700",
      style : "normal",
    },
  ]
})

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en" suppressHydrationWarning>
      <body
        className={`${sfPRO.className} ${sfPRO.className} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="flex flex-col h-full">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
